// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlanner.Infrastructure.Data;

#nullable disable

namespace StudyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyPlanner.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Language learning",
                            IsDeleted = false,
                            Name = "Vocabulary"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Software development",
                            IsDeleted = false,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Data structures & algorithms",
                            IsDeleted = false,
                            Name = "Algorithms"
                        });
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.ProgressRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinutesSpent")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ResultScore")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyItemId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressRecords");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("StudyItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2224df1-5f86-438e-8e2b-0d9253495856"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 12, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1730),
                            Description = "Intro to C#",
                            Difficulty = 0,
                            EstimatedDurationMinutes = 30,
                            IsCompleted = false,
                            IsDeleted = false,
                            NextReviewDate = new DateTime(2026, 7, 10, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1700),
                            Priority = 4,
                            Title = "Learn C# Basics",
                            Type = 2,
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("4ed4ecfa-0ad7-4fbc-a56d-8e7f4e4d87c5"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 12, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1740),
                            Description = "Implement quicksort",
                            Difficulty = 1,
                            EstimatedDurationMinutes = 45,
                            IsCompleted = false,
                            IsDeleted = false,
                            NextReviewDate = new DateTime(2026, 7, 11, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1740),
                            Priority = 3,
                            Title = "Sorting Algorithms",
                            Type = 1,
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("fa3d4c12-40fa-4936-922d-961311e628db"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1750),
                            Description = "Basic greetings",
                            Difficulty = 0,
                            EstimatedDurationMinutes = 20,
                            IsCompleted = false,
                            IsDeleted = false,
                            NextReviewDate = new DateTime(2026, 7, 12, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1740),
                            Priority = 2,
                            Title = "Spanish Greetings",
                            Type = 0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("06fac01c-1184-4e0d-bce1-b068e0f8dd81"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 12, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1750),
                            Description = "Study SOLID",
                            Difficulty = 2,
                            EstimatedDurationMinutes = 60,
                            IsCompleted = false,
                            IsDeleted = false,
                            NextReviewDate = new DateTime(2026, 7, 13, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1750),
                            Priority = 5,
                            Title = "Design Patterns",
                            Type = 2,
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPlannedItems")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPlannedMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudySessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudyItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyItemId");

                    b.HasIndex("StudySessionId");

                    b.ToTable("StudySessionItems");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 9, 28, 10, 442, DateTimeKind.Utc).AddTicks(1670),
                            Email = "demo@studyplanner.com",
                            FullName = "Demo User",
                            IsActive = true,
                            PasswordHash = "ijB+qBaQa257yaJeoHCrzR/fBHVJ4IHm+mpkiCk7GY0="
                        });
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.ProgressRecord", b =>
                {
                    b.HasOne("StudyPlanner.Domain.Entities.StudyItem", "StudyItem")
                        .WithMany()
                        .HasForeignKey("StudyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlanner.Domain.Entities.User", "User")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudyItem", b =>
                {
                    b.HasOne("StudyPlanner.Domain.Entities.Category", "Category")
                        .WithMany("StudyItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlanner.Domain.Entities.User", "User")
                        .WithMany("StudyItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudySession", b =>
                {
                    b.HasOne("StudyPlanner.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudySessionItem", b =>
                {
                    b.HasOne("StudyPlanner.Domain.Entities.StudyItem", "StudyItem")
                        .WithMany()
                        .HasForeignKey("StudyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlanner.Domain.Entities.StudySession", "StudySession")
                        .WithMany("SessionItems")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyItem");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.Category", b =>
                {
                    b.Navigation("StudyItems");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.StudySession", b =>
                {
                    b.Navigation("SessionItems");
                });

            modelBuilder.Entity("StudyPlanner.Domain.Entities.User", b =>
                {
                    b.Navigation("ProgressRecords");

                    b.Navigation("Sessions");

                    b.Navigation("StudyItems");
                });
#pragma warning restore 612, 618
        }
    }
}
